// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import AccommodationSection from "./AccommodationSection/AccommodationSection";
import CelebrationSection from "./CelebrationSection/CelebrationSection";
import CeremonySection from "./CeremonySection/CeremonySection";
import DateSection from "./DateSection/DateSection";
import DividerSection from "./DividerSection/DividerSection";
import DressCodeSection from "./DressCodeSection/DressCodeSection";
import GiftSection from "./GiftSection/GiftSection";
import HeroSection from "./HeroSection/HeroSection";
import InstagramSection from "./InstagramSection/InstagramSection";
import PhotoUploadSection from "./PhotoUploadSection/PhotoUploadSection";
import QRSection from "./QRSection/QRSection";
import QuoteSection from "./QuoteSection/QuoteSection";
import RSVPSection from "./RSVPSection/RSVPSection";

// ============================================
// COMPONENT REGISTRY
// ============================================
export const SECTION_COMPONENTS = {
  "accommodation": AccommodationSection,
  "celebration": CelebrationSection,
  "ceremony": CeremonySection,
  "date": DateSection,
  "divider": DividerSection,
  "dress_code": DressCodeSection,
  "gift": GiftSection,
  "hero": HeroSection,
  "instagram": InstagramSection,
  "photo_upload": PhotoUploadSection,
  "qr": QRSection,
  "quote": QuoteSection,
  "rsvp": RSVPSection,
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_COMPONENTS;
