// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import { AccommodationSectionMetadata } from "./AccommodationSection/AccommodationSection.metadata";
import { CelebrationSectionMetadata } from "./CelebrationSection/CelebrationSection.metadata";
import { CeremonySectionMetadata } from "./CeremonySection/CeremonySection.metadata";
import { DateSectionMetadata } from "./DateSection/DateSection.metadata";
import { DressCodeSectionMetadata } from "./DressCodeSection/DressCodeSection.metadata";
import { GiftSectionMetadata } from "./GiftSection/GiftSection.metadata";
import { HeroSectionMetadata } from "./HeroSection/HeroSection.metadata";
import { InstagramSectionMetadata } from "./InstagramSection/InstagramSection.metadata";
import { PhotoUploadSectionMetadata } from "./PhotoUploadSection/PhotoUploadSection.metadata";
import { QuoteSectionMetadata } from "./QuoteSection/QuoteSection.metadata";
import { RSVPSectionMetadata } from "./RSVPSection/RSVPSection.metadata";

// ============================================
// METADATA REGISTRY
// ============================================
export const SECTION_METADATA = {
  "accommodation": AccommodationSectionMetadata,
  "celebration": CelebrationSectionMetadata,
  "ceremony": CeremonySectionMetadata,
  "date": DateSectionMetadata,
  "dress_code": DressCodeSectionMetadata,
  "gift": GiftSectionMetadata,
  "hero": HeroSectionMetadata,
  "instagram": InstagramSectionMetadata,
  "photo_upload": PhotoUploadSectionMetadata,
  "quote": QuoteSectionMetadata,
  "rsvp": RSVPSectionMetadata,
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_METADATA;

export function isSectionKey(key: string): key is SectionKey {
  return key in SECTION_METADATA;
}
