// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import { z } from "zod";
import { AccommodationSectionSettingsSchema } from "./AccommodationSection/AccommodationSection.metadata";
import { CelebrationSectionSettingsSchema } from "./CelebrationSection/CelebrationSection.metadata";
import { CeremonySectionSettingsSchema } from "./CeremonySection/CeremonySection.metadata";
import { DateSectionSettingsSchema } from "./DateSection/DateSection.metadata";
import { DividerSectionSettingsSchema } from "./DividerSection/DividerSection.metadata";
import { DressCodeSectionSettingsSchema } from "./DressCodeSection/DressCodeSection.metadata";
import { GiftSectionSettingsSchema } from "./GiftSection/GiftSection.metadata";
import { HeroSectionSettingsSchema } from "./HeroSection/HeroSection.metadata";
import { InstagramSectionSettingsSchema } from "./InstagramSection/InstagramSection.metadata";
import { PhotoUploadSectionSettingsSchema } from "./PhotoUploadSection/PhotoUploadSection.metadata";
import { QRSectionSettingsSchema } from "./QRSection/QRSection.metadata";
import { QuoteSectionSettingsSchema } from "./QuoteSection/QuoteSection.metadata";
import { RSVPSectionSettingsSchema } from "./RSVPSection/RSVPSection.metadata";

// ============================================
// SCHEMA REGISTRY
// ============================================
export const SECTION_SCHEMAS = {
  "accommodation": AccommodationSectionSettingsSchema,
  "celebration": CelebrationSectionSettingsSchema,
  "ceremony": CeremonySectionSettingsSchema,
  "date": DateSectionSettingsSchema,
  "divider": DividerSectionSettingsSchema,
  "dress_code": DressCodeSectionSettingsSchema,
  "gift": GiftSectionSettingsSchema,
  "hero": HeroSectionSettingsSchema,
  "instagram": InstagramSectionSettingsSchema,
  "photo_upload": PhotoUploadSectionSettingsSchema,
  "qr": QRSectionSettingsSchema,
  "quote": QuoteSectionSettingsSchema,
  "rsvp": RSVPSectionSettingsSchema,
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_SCHEMAS;

// Helper para obtener schema por key
export function getSectionSettingsSchema(key: string): z.ZodSchema {
  const schema = SECTION_SCHEMAS[key as SectionKey];
  return schema ?? z.object({});
}
