apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: caddy-logs-*
    jsonData:
      timeField: timestamp
      esVersion: 9.1.2
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level
    editable: true
