#!/usr/bin/env tsx

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { PrismaClient } from "../app/generated/prisma/index.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SECTIONS_DIR = path.resolve(__dirname, "../components/sections");
const OUTPUT_FILE_COMPONENTS = path.resolve(SECTIONS_DIR, "index.ts");
const OUTPUT_FILE_METADATA = path.resolve(SECTIONS_DIR, "metadata.ts");
const OUTPUT_FILE_FORMS = path.resolve(SECTIONS_DIR, "forms.ts");
const OUTPUT_FILE_SCHEMAS = path.resolve(SECTIONS_DIR, "schemas.ts");

const prisma = new PrismaClient();

interface SectionInfo {
  folderName: string;
  componentName: string;
  metadataName: string;
  settingsFormName: string;
  key: string;
  name: string;
  description: string;
  icon: string;
  defaultOrder: number;
  defaultEnabled: boolean;
}

async function discoverSections(): Promise<SectionInfo[]> {
  console.log("🔍 Escaneando secciones en:", SECTIONS_DIR);

  const entries = await fs.readdir(SECTIONS_DIR, { withFileTypes: true });
  const sections: SectionInfo[] = [];

  for (const entry of entries) {
    // Solo carpetas que terminen en "Section"
    if (!entry.isDirectory() || !entry.name.endsWith("Section")) {
      continue;
    }

    const folderPath = path.join(SECTIONS_DIR, entry.name);
    const metadataFile = path.join(folderPath, `${entry.name}.metadata.ts`);

    // Verificar que exista el archivo metadata
    try {
      await fs.access(metadataFile);
    } catch {
      console.warn(`⚠️  Skipping ${entry.name}: no metadata file found`);
      continue;
    }

    // Importar metadata dinámicamente (más seguro que regex)
    try {
      const metadataModule = await import(
        `file://${metadataFile}?update=${Date.now()}`
      );
      const metadataName = `${entry.name}Metadata`;
      const metadata = metadataModule[metadataName];

      if (!metadata || !metadata.key) {
        console.warn(
          `⚠️  Skipping ${entry.name}: no metadata object found or missing key`,
        );
        continue;
      }

      sections.push({
        folderName: entry.name,
        componentName: entry.name,
        metadataName,
        settingsFormName: `${entry.name}SettingsForm`,
        key: metadata.key,
        name: metadata.name || entry.name,
        description: metadata.description || "",
        icon: metadata.icon || "📄",
        defaultOrder:
          typeof metadata.defaultOrder === "number"
            ? metadata.defaultOrder
            : 999,
        defaultEnabled: metadata.defaultEnabled === true,
      });

      console.log(`  ✓ ${entry.name} (key: ${metadata.key})`);
    } catch (error) {
      console.warn(
        `⚠️  Skipping ${entry.name}: error importing metadata`,
        error,
      );
      continue;
    }
  }

  return sections;
}

function generateComponentsCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import ${s.componentName} from "./${s.folderName}/${s.componentName}";`,
    )
    .join("\n");

  const componentRegistry = sections
    .map((s) => `  "${s.key}": ${s.componentName},`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

${imports}

// ============================================
// COMPONENT REGISTRY
// ============================================
export const SECTION_COMPONENTS = {
${componentRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_COMPONENTS;
`;
}

function generateMetadataCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import { ${s.metadataName} } from "./${s.folderName}/${s.componentName}.metadata";`,
    )
    .join("\n");

  const metadataRegistry = sections
    .map((s) => `  "${s.key}": ${s.metadataName},`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

${imports}

// ============================================
// METADATA REGISTRY
// ============================================
export const SECTION_METADATA = {
${metadataRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_METADATA;

export function isSectionKey(key: string): key is SectionKey {
  return key in SECTION_METADATA;
}
`;
}

function generateFormsCode(sections: SectionInfo[]): string {
  const dynamicImports = sections
    .map(
      (s) =>
        `  "${s.key}": () => import("./${s.folderName}/${s.componentName}Settings").then(mod => ({ default: mod.${s.settingsFormName} })),`,
    )
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import type React from "react";

// ============================================
// SETTINGS FORMS DYNAMIC IMPORTS
// ============================================
// Cada form se carga solo cuando se necesita (code splitting)
export const SECTION_SETTINGS_FORM_IMPORTS: Record<
  string,
  () => Promise<{ default: React.ComponentType<any> }>
> = {
${dynamicImports}
};

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_SETTINGS_FORM_IMPORTS;
`;
}

function generateSchemasCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import { ${s.componentName}SettingsSchema } from "./${s.folderName}/${s.componentName}.metadata";`,
    )
    .join("\n");

  const schemaRegistry = sections
    .map((s) => `  "${s.key}": ${s.componentName}SettingsSchema,`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import { z } from "zod";
${imports}

// ============================================
// SCHEMA REGISTRY
// ============================================
export const SECTION_SCHEMAS = {
${schemaRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_SCHEMAS;

// Helper para obtener schema por key
export function getSectionSettingsSchema(key: string): z.ZodSchema {
  const schema = SECTION_SCHEMAS[key as SectionKey];
  return schema ?? z.object({});
}
`;
}

async function syncDatabase(sections: SectionInfo[]) {
  console.log("💾 Syncing with database...\n");

  // 1. Obtener todas las secciones actuales en BD
  const existingSections = await prisma.sectionConfiguration.findMany();
  const existingKeys = new Set(existingSections.map((s) => s.key));
  const discoveredKeys = new Set(sections.map((s) => s.key));

  // 2. Identificar secciones que ya no existen en el código
  const sectionsToDelete = existingSections.filter(
    (s) => !discoveredKeys.has(s.key),
  );

  // 3. Eliminar secciones obsoletas
  if (sectionsToDelete.length > 0) {
    console.log("🗑️  Removing deleted sections:\n");
    for (const section of sectionsToDelete) {
      try {
        await prisma.sectionConfiguration.delete({
          where: { key: section.key },
        });
        console.log(`  ✗ Deleted: ${section.key}`);
      } catch (error) {
        console.error(`  ✗ Error deleting ${section.key}:`, error);
      }
    }
    console.log("");
  }

  // 4. Ordenar por defaultOrder
  const sortedSections = [...sections].sort(
    (a, b) => a.defaultOrder - b.defaultOrder,
  );

  // 5. Upsert secciones nuevas con orden temporal negativo
  console.log("📝 Upserting sections (temp order):\n");
  for (let i = 0; i < sortedSections.length; i++) {
    const section = sortedSections[i];

    try {
      await prisma.sectionConfiguration.upsert({
        where: { key: section.key },
        update: {
          // Si ya existe, solo actualizar con orden temporal negativo
          order: -2000 - i,
        },
        create: {
          key: section.key,
          isEnabled: section.defaultEnabled,
          order: -2000 - i, // Orden temporal negativo para evitar conflictos
          settings: {}, // Settings vacíos por defecto
        },
      });
      const action = existingKeys.has(section.key) ? "✓" : "✓ Created";
      console.log(`  ${action}: ${section.key}`);
    } catch (error) {
      console.error(`  ✗ Error syncing ${section.key}:`, error);
    }
  }

  // 6. Ahora actualizar todos los order a los valores finales
  console.log("\n📝 Updating final order:\n");
  for (let i = 0; i < sortedSections.length; i++) {
    const section = sortedSections[i];

    try {
      await prisma.sectionConfiguration.update({
        where: { key: section.key },
        data: {
          order: i,
        },
      });
      console.log(`  ✓: ${section.key} (order: ${i})`);
    } catch (error) {
      console.error(`  ✗ Error updating order for ${section.key}:`, error);
    }
  }

  console.log("\n✅ Database sync completed!");
}

async function main() {
  console.log("🚀 Syncing sections...\n");

  try {
    // 1. Descubrir todas las secciones
    const sections = await discoverSections();

    if (sections.length === 0) {
      console.error("❌ No sections found!");
      process.exit(1);
    }

    console.log(`\n✅ Found ${sections.length} sections\n`);

    // 2. Generar código de los registries
    const componentsCode = generateComponentsCode(sections);
    const metadataCode = generateMetadataCode(sections);
    const formsCode = generateFormsCode(sections);
    const schemasCode = generateSchemasCode(sections);

    // 3. Escribir archivos
    await fs.writeFile(OUTPUT_FILE_COMPONENTS, componentsCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_METADATA, metadataCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_FORMS, formsCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_SCHEMAS, schemasCode, "utf-8");
    console.log(`📝 Generated registries:`);
    console.log(`   - ${OUTPUT_FILE_COMPONENTS}`);
    console.log(`   - ${OUTPUT_FILE_METADATA}`);
    console.log(`   - ${OUTPUT_FILE_FORMS}`);
    console.log(`   - ${OUTPUT_FILE_SCHEMAS}\n`);

    // 4. Sincronizar con la BD
    await syncDatabase(sections);

    // 5. Resumen
    console.log("\n✅ Sync completed successfully!");
    console.log(`\nRegistered sections:`);
    sections.forEach((s) => {
      console.log(`  - ${s.key} (${s.folderName})`);
    });
  } catch (error) {
    console.error("❌ Error syncing sections:", error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
