#!/usr/bin/env tsx

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SECTIONS_DIR = path.resolve(__dirname, "../components/sections");
const OUTPUT_FILE_COMPONENTS = path.resolve(SECTIONS_DIR, "index.ts");
const OUTPUT_FILE_METADATA = path.resolve(SECTIONS_DIR, "metadata.ts");
const OUTPUT_FILE_FORMS = path.resolve(SECTIONS_DIR, "forms.ts");
const OUTPUT_FILE_SCHEMAS = path.resolve(SECTIONS_DIR, "schemas.ts");

interface SectionInfo {
  folderName: string;
  componentName: string;
  metadataName: string;
  settingsFormName: string;
  key: string;
  name: string;
  description: string;
  icon: string;
  defaultOrder: number;
  defaultEnabled: boolean;
}

async function discoverSections(): Promise<SectionInfo[]> {
  console.log("🔍 Escaneando secciones en:", SECTIONS_DIR);

  const entries = await fs.readdir(SECTIONS_DIR, { withFileTypes: true });
  const sections: SectionInfo[] = [];

  for (const entry of entries) {
    // Solo carpetas que terminen en "Section"
    if (!entry.isDirectory() || !entry.name.endsWith("Section")) {
      continue;
    }

    const folderPath = path.join(SECTIONS_DIR, entry.name);
    const metadataFile = path.join(folderPath, `${entry.name}.metadata.ts`);

    // Verificar que exista el archivo metadata
    try {
      await fs.access(metadataFile);
    } catch {
      console.warn(`⚠️  Skipping ${entry.name}: no metadata file found`);
      continue;
    }

    // Importar metadata dinámicamente (más seguro que regex)
    try {
      const metadataModule = await import(
        `file://${metadataFile}?update=${Date.now()}`
      );
      const metadataName = `${entry.name}Metadata`;
      const metadata = metadataModule[metadataName];

      if (!metadata || !metadata.key) {
        console.warn(
          `⚠️  Skipping ${entry.name}: no metadata object found or missing key`,
        );
        continue;
      }

      sections.push({
        folderName: entry.name,
        componentName: entry.name,
        metadataName,
        settingsFormName: `${entry.name}SettingsForm`,
        key: metadata.key,
        name: metadata.name || entry.name,
        description: metadata.description || "",
        icon: metadata.icon || "📄",
        defaultOrder:
          typeof metadata.defaultOrder === "number"
            ? metadata.defaultOrder
            : 999,
        defaultEnabled: metadata.defaultEnabled === true,
      });

      console.log(`  ✓ ${entry.name} (key: ${metadata.key})`);
    } catch (error) {
      console.warn(
        `⚠️  Skipping ${entry.name}: error importing metadata`,
        error,
      );
      continue;
    }
  }

  return sections;
}

function generateComponentsCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import ${s.componentName} from "./${s.folderName}/${s.componentName}";`,
    )
    .join("\n");

  const componentRegistry = sections
    .map((s) => `  "${s.key}": ${s.componentName},`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

${imports}

// ============================================
// COMPONENT REGISTRY
// ============================================
export const SECTION_COMPONENTS = {
${componentRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_COMPONENTS;
`;
}

function generateMetadataCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import { ${s.metadataName} } from "./${s.folderName}/${s.componentName}.metadata";`,
    )
    .join("\n");

  const metadataRegistry = sections
    .map((s) => `  "${s.key}": ${s.metadataName},`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

${imports}

// ============================================
// METADATA REGISTRY
// ============================================
export const SECTION_METADATA = {
${metadataRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_METADATA;

export function isSectionKey(key: string): key is SectionKey {
  return key in SECTION_METADATA;
}
`;
}

function generateFormsCode(sections: SectionInfo[]): string {
  const dynamicImports = sections
    .map(
      (s) =>
        `  "${s.key}": () => import("./${s.folderName}/${s.componentName}Settings").then(mod => ({ default: mod.${s.settingsFormName} })),`,
    )
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import type { ComponentType } from "react";

// ============================================
// SETTINGS FORMS DYNAMIC IMPORTS
// ============================================
// Cada form se carga solo cuando se necesita (code splitting)
export const SECTION_SETTINGS_FORM_IMPORTS: Record<
  string,
  () => Promise<{ default: ComponentType<any> }>
> = {
${dynamicImports}
};

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_SETTINGS_FORM_IMPORTS;
`;
}

function generateSchemasCode(sections: SectionInfo[]): string {
  const imports = sections
    .map(
      (s) =>
        `import { ${s.componentName}SettingsSchema } from "./${s.folderName}/${s.componentName}.metadata";`,
    )
    .join("\n");

  const schemaRegistry = sections
    .map((s) => `  "${s.key}": ${s.componentName}SettingsSchema,`)
    .join("\n");

  return `// ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/sync-sections.ts
// Run: pnpm run internal:sync-sections

import { z } from "zod";
${imports}

// ============================================
// SCHEMA REGISTRY
// ============================================
export const SECTION_SCHEMAS = {
${schemaRegistry}
} as const;

// ============================================
// TYPES
// ============================================
export type SectionKey = keyof typeof SECTION_SCHEMAS;

// Helper para obtener schema por key
export function getSectionSettingsSchema(key: string): z.ZodSchema {
  const schema = SECTION_SCHEMAS[key as SectionKey];
  return schema ?? z.object({});
}
`;
}

// NOTE: Database sync removed - sections are now managed via /backoffice/structure UI
// This script only generates the TypeScript registries

async function main() {
  console.log("🚀 Syncing sections registries (NOT touching database)...\n");

  try {
    // 1. Descubrir todas las secciones
    const sections = await discoverSections();

    if (sections.length === 0) {
      console.error("❌ No sections found!");
      process.exit(1);
    }

    console.log(`\n✅ Found ${sections.length} sections\n`);

    // 2. Generar código de los registries
    const componentsCode = generateComponentsCode(sections);
    const metadataCode = generateMetadataCode(sections);
    const formsCode = generateFormsCode(sections);
    const schemasCode = generateSchemasCode(sections);

    // 3. Escribir archivos
    await fs.writeFile(OUTPUT_FILE_COMPONENTS, componentsCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_METADATA, metadataCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_FORMS, formsCode, "utf-8");
    await fs.writeFile(OUTPUT_FILE_SCHEMAS, schemasCode, "utf-8");
    console.log(`📝 Generated registries:`);
    console.log(`   - ${OUTPUT_FILE_COMPONENTS}`);
    console.log(`   - ${OUTPUT_FILE_METADATA}`);
    console.log(`   - ${OUTPUT_FILE_FORMS}`);
    console.log(`   - ${OUTPUT_FILE_SCHEMAS}\n`);

    // 4. Resumen
    console.log("✅ Sync completed successfully!");
    console.log("\nAvailable sections (use backoffice UI to add/remove):");
    sections.forEach((s) => {
      console.log(`  - ${s.key} (${s.folderName})`);
    });
    console.log("\n💡 Tip: Go to /backoffice/structure to manage sections\n");
  } catch (error) {
    console.error("❌ Error syncing sections:", error);
    process.exit(1);
  }
}

main();
